/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	apaardevv1alpha1 "github.com/apaarshrm39/rgp/pkg/apis/apaar.dev/v1alpha1"
	versioned "github.com/apaarshrm39/rgp/pkg/client/clientset/versioned"
	internalinterfaces "github.com/apaarshrm39/rgp/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/apaarshrm39/rgp/pkg/client/listers/apaar.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RgpInformer provides access to a shared informer and lister for
// Rgps.
type RgpInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RgpLister
}

type rgpInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRgpInformer constructs a new informer for Rgp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRgpInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRgpInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRgpInformer constructs a new informer for Rgp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRgpInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApaarV1alpha1().Rgps(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApaarV1alpha1().Rgps(namespace).Watch(context.TODO(), options)
			},
		},
		&apaardevv1alpha1.Rgp{},
		resyncPeriod,
		indexers,
	)
}

func (f *rgpInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRgpInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rgpInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apaardevv1alpha1.Rgp{}, f.defaultInformer)
}

func (f *rgpInformer) Lister() v1alpha1.RgpLister {
	return v1alpha1.NewRgpLister(f.Informer().GetIndexer())
}
